<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-14T12:35:56Z" name="TV 2 Sumo Automation Test Suite" finished-at="2019-06-14T12:36:33Z" duration-ms="36222">
    <groups>
    </groups>
    <test started-at="2019-06-14T12:35:56Z" name="TV 2 sumo Test Cases" finished-at="2019-06-14T12:36:33Z" duration-ms="36222">
      <class name="sumo.qa.testcases.FrontpageTest">
        <test-method is-config="true" signature="setExtent()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:35:56Z" name="setExtent" finished-at="2019-06-14T12:35:57Z" duration-ms="143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:35:57Z" name="setUp" finished-at="2019-06-14T12:36:04Z" duration-ms="6980" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="LogginnFunction_Testcase()[pri:1, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:04Z" name="LogginnFunction_Testcase" finished-at="2019-06-14T12:36:06Z" duration-ms="2571" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[LogginFunction is not working expected [Saranraj123] but found [Saranraj]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: LogginFunction is not working expected [Saranraj123] but found [Saranraj]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at sumo.qa.testcases.FrontpageTest.LogginnFunction_Testcase(FrontpageTest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogginnFunction_Testcase -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:06Z" name="tearDown" finished-at="2019-06-14T12:36:07Z" duration-ms="1261" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LogginnFunction_Testcase status=FAILURE method=FrontpageTest.LogginnFunction_Testcase()[pri:1, instance:sumo.qa.testcases.FrontpageTest@4cc451f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:07Z" name="setUp" finished-at="2019-06-14T12:36:14Z" duration-ms="6544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="GlemtPassordLink_Click_Testcase()[pri:2, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:14Z" name="GlemtPassordLink_Click_Testcase" finished-at="2019-06-14T12:36:14Z" duration-ms="297" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Glemt Passordlink is not working expected [Få passord123] but found [Få passord]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Glemt Passordlink is not working expected [Få passord123] but found [Få passord]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at sumo.qa.testcases.FrontpageTest.GlemtPassordLink_Click_Testcase(FrontpageTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GlemtPassordLink_Click_Testcase -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:14Z" name="tearDown" finished-at="2019-06-14T12:36:15Z" duration-ms="1180" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=GlemtPassordLink_Click_Testcase status=FAILURE method=FrontpageTest.GlemtPassordLink_Click_Testcase()[pri:2, instance:sumo.qa.testcases.FrontpageTest@4cc451f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:15Z" name="setUp" finished-at="2019-06-14T12:36:22Z" duration-ms="6466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="NyBruker_FåtilgangNåLink_Click_Testcase()[pri:3, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:22Z" name="NyBruker_FåtilgangNåLink_Click_Testcase" finished-at="2019-06-14T12:36:23Z" duration-ms="1124" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ny bruker? Få tilgang nå! Link is not working expected [Registrer ny bruker123] but found [Registrer ny bruker]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ny bruker? Få tilgang nå! Link is not working expected [Registrer ny bruker123] but found [Registrer ny bruker]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at sumo.qa.testcases.FrontpageTest.NyBruker_FåtilgangNåLink_Click_Testcase(FrontpageTest.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NyBruker_FåtilgangNåLink_Click_Testcase -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:23Z" name="tearDown" finished-at="2019-06-14T12:36:24Z" duration-ms="1115" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=NyBruker_FåtilgangNåLink_Click_Testcase status=FAILURE method=FrontpageTest.NyBruker_FåtilgangNåLink_Click_Testcase()[pri:3, instance:sumo.qa.testcases.FrontpageTest@4cc451f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:24Z" name="setUp" finished-at="2019-06-14T12:36:31Z" duration-ms="6998" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="logginnBtn_Click_Testcase()[pri:4, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:31Z" name="logginnBtn_Click_Testcase" finished-at="2019-06-14T12:36:31Z" duration-ms="119" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logginn Button is not working  expected [Logg inn123] but found [Logg inn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logginn Button is not working  expected [Logg inn123] but found [Logg inn]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at sumo.qa.testcases.FrontpageTest.logginnBtn_Click_Testcase(FrontpageTest.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logginnBtn_Click_Testcase -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:31Z" name="tearDown" finished-at="2019-06-14T12:36:32Z" duration-ms="1167" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logginnBtn_Click_Testcase status=FAILURE method=FrontpageTest.logginnBtn_Click_Testcase()[pri:4, instance:sumo.qa.testcases.FrontpageTest@4cc451f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:sumo.qa.testcases.FrontpageTest@4cc451f2]" started-at="2019-06-14T12:36:32Z" name="endReport" finished-at="2019-06-14T12:36:33Z" duration-ms="228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- sumo.qa.testcases.FrontpageTest -->
    </test> <!-- TV 2 sumo Test Cases -->
  </suite> <!-- TV 2 Sumo Automation Test Suite -->
</testng-results>
